### ISSUE TITLE
Compatibility with Oasis Core 21.2

### ISSUE THREAD

**Issue by lougon** [oasisprotocol/oasis-core-rosetta-gateway#211] opened 2021-06-08 07:21 UTC
use oasis_core 21.2 version
oasis-core-rosetta-gateway 1.1.1
rpc:block
block:3610570

 post body
{
    "network_identifier": {
	    "blockchain": "Oasis",
	    "network": "53852332637bacb61b91b6411ab4095168ba02a50be4c3f82448438826f23898"
	},
    "block_identifier": {
        "index": 3610570
    }
}

Returned result
{
    "code": 14,
    "message": "unable to get transactions",
    "retriable": true
}

**Comment by kostko** [comment] 2021-06-08 07:49
The current version of the Rosetta gateway (v1.1.1) has only been tested with Oasis Core 21.1.x. Can you reproduce the issue with that version?

**Comment by lougon** [comment] 2021-06-09 03:33
There is no problem with oasis core 21.1. X
oasis core 21.2 version have problems
You try block:3610570

**Comment by lougon** [comment] 2021-06-09 03:35
There are also many block problems, 3610570 is just one of them

**Comment by kostko** [comment] 2021-06-09 08:13
This is expected due to some breaking event changes in Oasis Core 21.2. As mentioned, Rosetta gateway v1.1.1 targets Oasis Core 21.1 and if you need to use Rosetta, you should currently use Oasis Core 21.1 until a new version of the Rosetta gateway is released. We'll use this issue to track the necessary changes.

**Comment by kostko** [comment] 2021-06-16 11:08
Actually what you describe may be caused by the issue fixed in https://github.com/oasisprotocol/oasis-core/pull/4033. The fix is planned to be released as part of Oasis Core 21.2.2, but will require a node re-sync from scratch since the problematic events have been incorrectly stored.

**Comment by lougon** [comment] 2021-07-16 08:59
I used oasis core 21.2.7 and resynchronized the nodes

But there will be problems.

Can I only use 21.1.X?

**Comment by tjanez** [comment] 2021-08-11 08:20
@lougon, the latest `master` of Rosetta Gateway should be compatible with Oasis Core 21.2.x and we'll release a new version of Rosetta Gateway (1.2.0) that will be compatible with it soon.

**Closed** 2021-08-11 12:13 UTC
Labels: c:deps
